/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package scacp;

import java.util.HashMap;
import java.util.Set;

/**
 *
 * @author cleber
 */
public class CartaoLocalizar extends javax.swing.JDialog {
    Cartao cartao;
    HashMap<Integer, Cartao> cartoes;
    /**
     * Creates new form CartaoLocalizar
     */
    public CartaoLocalizar(java.awt.Frame parent, boolean modal, HashMap<Integer, Cartao> cartoes, Cartao cartao) {
        super(parent, modal);
        this.cartoes = cartoes;
        this.cartao = cartao;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumeroinscricao = new javax.swing.JLabel();
        txfNumeroInscricao = new javax.swing.JTextField();
        btnLocalizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCartoes = new javax.swing.JList();
        btnAbrir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Localizar Cartão");
        setPreferredSize(new java.awt.Dimension(300, 400));

        lblNumeroinscricao.setText("Número Inscrição:");

        txfNumeroInscricao.setVisible(false);

        btnLocalizar.setText("Localizar");
        btnLocalizar.setVisible(false);
        btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarActionPerformed(evt);
            }
        });

        listCartoes.setModel(new javax.swing.AbstractListModel() {
            public int getSize() {
                return cartoes.size();
            }
            public Object getElementAt(int i) {
                Set numerosInscricao = cartoes.keySet();
                return numerosInscricao.toArray()[i];
            }
        });
        listCartoes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listCartoes);

        btnAbrir.setText("Abrir");
        if(cartoes.isEmpty()){
            btnAbrir.setEnabled(false);
        }
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAbrir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNumeroinscricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfNumeroInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLocalizar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroinscricao)
                    .addComponent(txfNumeroInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLocalizar))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbrir)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLocalizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        cartao.setMarcacao(cartoes.get((int) listCartoes.getSelectedValue()).getMarcacao());
        cartao.setNota(cartoes.get((int) listCartoes.getSelectedValue()).getNota());
        cartao.setNumeroInscricao(cartoes.get((int) listCartoes.getSelectedValue()).getNumeroInscricao());
        cartao.setCartaoSalvo(cartoes.get((int) listCartoes.getSelectedValue()).isCartaoSalvo());
        dispose();
    }//GEN-LAST:event_btnAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNumeroinscricao;
    private javax.swing.JList listCartoes;
    private javax.swing.JTextField txfNumeroInscricao;
    // End of variables declaration//GEN-END:variables
}
