/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package scacp;

import javax.swing.ButtonGroup;

/**
 *
 * @author cleber
 */
public class FormularioQuestaoVF extends javax.swing.JPanel {
    private int numeroQuestao, numeroInscricao;
    
    /**
     * Creates new form FormularioQuestaoME
     */
    public FormularioQuestaoVF(int numeroQuestao, int numeroInscricao) {
        this.numeroQuestao = numeroQuestao;
        this.numeroInscricao = numeroInscricao;
        initComponents();
    }

    public ButtonGroup getBtnGrupoAlternativas() {
        return gbtnAlternativas;
    }

    public void setBtnGrupoAlternativas(ButtonGroup btnGrupoAlternativas) {
        this.gbtnAlternativas = btnGrupoAlternativas;
    }

    public int getNumeroQuestao() {
        return numeroQuestao;
    }

    public void setNumeroQuestao(int numeroQuestao) {
        this.numeroQuestao = numeroQuestao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtnAlternativas = new javax.swing.ButtonGroup();
        lblNumeroQuestao = new javax.swing.JLabel();
        rbtA = new javax.swing.JRadioButton();
        rbtB = new javax.swing.JRadioButton();
        rbtMultipla = new javax.swing.JRadioButton();
        rbtBranco = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNumeroQuestao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroQuestao.setText(String.format("%2d", numeroQuestao));

        gbtnAlternativas.add(rbtA);
        rbtA.setText("V");

        gbtnAlternativas.add(rbtB);
        rbtB.setText("F");

        gbtnAlternativas.add(rbtMultipla);
        rbtMultipla.setText("#");

        gbtnAlternativas.add(rbtBranco);
        rbtBranco.setText("*");
        if(numeroInscricao == 9999990){
            rbtBranco.setVisible(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rbtB)
            .addComponent(rbtMultipla)
            .addComponent(rbtBranco)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(lblNumeroQuestao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addComponent(rbtA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblNumeroQuestao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtMultipla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtBranco)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup gbtnAlternativas;
    private javax.swing.JLabel lblNumeroQuestao;
    private javax.swing.JRadioButton rbtA;
    private javax.swing.JRadioButton rbtB;
    private javax.swing.JRadioButton rbtBranco;
    private javax.swing.JRadioButton rbtMultipla;
    // End of variables declaration//GEN-END:variables
}
