/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package scacp;

/**
 *
 * @author Cleber
 */
public class JanelaSobre extends javax.swing.JFrame {

    /**
     * Esta classe é responsável por criar uma janela com informações referentes ao software, 
     * como nome, versão e desenvolvedores
     */
    public JanelaSobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSCACPExtenso = new javax.swing.JLabel();
        lblDesenvolvedores = new javax.swing.JLabel();
        lblNomeCleber = new javax.swing.JLabel();
        lblEmailCleber = new javax.swing.JLabel();
        lblEmailLarissa = new javax.swing.JLabel();
        lblNomeLarissa = new javax.swing.JLabel();
        lblEmailLeticia = new javax.swing.JLabel();
        lblNomeLeticia = new javax.swing.JLabel();
        lblFotoCleber = new javax.swing.JLabel();
        lblFotoLeticia = new javax.swing.JLabel();
        lblFotoLarissa = new javax.swing.JLabel();
        lblIconeGameOfLife = new javax.swing.JLabel();
        lblUFG = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        lblINF = new javax.swing.JLabel();
        lblEngenhariaSoftware = new javax.swing.JLabel();
        lblProfessor = new javax.swing.JLabel();
        lblNomeWanderley = new javax.swing.JLabel();
        lblNomeDisciplina = new javax.swing.JLabel();
        lblDisciplina = new javax.swing.JLabel();
        lblSCACPSigla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sobre");
        setName("frameSobre"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 480));
        setResizable(false);

        lblSCACPExtenso.setFont(new java.awt.Font("Ubuntu", 1, 50)); // NOI18N
        lblSCACPExtenso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSCACPExtenso.setText("SCACP");

        lblDesenvolvedores.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblDesenvolvedores.setText("Desenvolvedores");

        lblNomeCleber.setText("Cleber de Souza Alcântara");

        lblEmailCleber.setFont(new java.awt.Font("Ubuntu", 2, 13)); // NOI18N
        lblEmailCleber.setText("cleber.93cd@gmail.com");

        lblEmailLarissa.setFont(new java.awt.Font("Ubuntu", 2, 13)); // NOI18N
        lblEmailLarissa.setText("larissamean@gmail.com");

        lblNomeLarissa.setText("Larissa Angélica Siqueira Nunes");

        lblEmailLeticia.setFont(new java.awt.Font("Ubuntu", 2, 13)); // NOI18N
        lblEmailLeticia.setText("leticia_nb1@hotmail.com");

        lblNomeLeticia.setText("Letícia Nunes Borges");

        lblFotoCleber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cleber.png"))); // NOI18N

        lblFotoLeticia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/leticia.png"))); // NOI18N

        lblFotoLarissa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/larissa.png"))); // NOI18N

        lblIconeGameOfLife.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconeGameOfLife.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo.png"))); // NOI18N

        lblUFG.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblUFG.setText("Universidade Federal de Goiás");

        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblINF.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblINF.setText("Instituto de Informática");

        lblEngenhariaSoftware.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblEngenhariaSoftware.setText("Engenharia de Software");

        lblProfessor.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblProfessor.setText("Professor");

        lblNomeWanderley.setText("Wanderley de Souza Alencar");

        lblNomeDisciplina.setText("Construção de Software");

        lblDisciplina.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblDisciplina.setText("Disciplina");

        lblSCACPSigla.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        lblSCACPSigla.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSCACPSigla.setText("<html>Sistema de Correção<br />Automática de Cartões<br />de Provas</html>");
        lblSCACPSigla.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUFG)
                            .addComponent(lblINF)
                            .addComponent(lblEngenhariaSoftware)
                            .addComponent(lblProfessor)
                            .addComponent(lblDisciplina)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNomeDisciplina)
                                    .addComponent(lblNomeWanderley))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDesenvolvedores)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFotoLeticia)
                                    .addComponent(lblFotoLarissa)
                                    .addComponent(lblFotoCleber))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblEmailLeticia))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNomeLarissa)
                                            .addComponent(lblNomeLeticia)
                                            .addComponent(lblNomeCleber)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblEmailLarissa)
                                                    .addComponent(lblEmailCleber)))))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblIconeGameOfLife)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSCACPExtenso)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblSCACPSigla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconeGameOfLife)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSCACPExtenso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSCACPSigla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDesenvolvedores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomeCleber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEmailCleber))
                            .addComponent(lblFotoCleber))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomeLarissa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEmailLarissa))
                            .addComponent(lblFotoLarissa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomeLeticia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEmailLeticia))
                            .addComponent(lblFotoLeticia)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUFG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblINF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEngenhariaSoftware)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDisciplina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomeDisciplina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProfessor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomeWanderley))
                    .addComponent(separator))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("Jogo da Vida (Game Of Life) - Versão 1.0\nDesenvolvedores:\nCleber de Souza Alcântara\nLarissa Nunes\nLetícia Nunes Borges");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaSobre().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDesenvolvedores;
    private javax.swing.JLabel lblDisciplina;
    private javax.swing.JLabel lblEmailCleber;
    private javax.swing.JLabel lblEmailLarissa;
    private javax.swing.JLabel lblEmailLeticia;
    private javax.swing.JLabel lblEngenhariaSoftware;
    private javax.swing.JLabel lblFotoCleber;
    private javax.swing.JLabel lblFotoLarissa;
    private javax.swing.JLabel lblFotoLeticia;
    private javax.swing.JLabel lblINF;
    private javax.swing.JLabel lblIconeGameOfLife;
    private javax.swing.JLabel lblNomeCleber;
    private javax.swing.JLabel lblNomeDisciplina;
    private javax.swing.JLabel lblNomeLarissa;
    private javax.swing.JLabel lblNomeLeticia;
    private javax.swing.JLabel lblNomeWanderley;
    private javax.swing.JLabel lblProfessor;
    private javax.swing.JLabel lblSCACPExtenso;
    private javax.swing.JLabel lblSCACPSigla;
    private javax.swing.JLabel lblUFG;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables
}
