/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package scacp;

/**
 *
 * @author cleber
 */
public class ProvaFormulario extends javax.swing.JDialog {
    Prova prova;
    /**
     * Creates new form ProvaFormulario
     */
    public ProvaFormulario(java.awt.Frame parent, boolean modal, Prova prova) {
        super(parent, modal);
        this.prova = prova;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTipoProva = new javax.swing.JLabel();
        cmbbTipoProva = new javax.swing.JComboBox();
        lblQntQuestoes = new javax.swing.JLabel();
        spnQntQuestoes = new javax.swing.JSpinner();
        pnlEscalaPontuacao = new javax.swing.JPanel();
        lblPontucaoMinima = new javax.swing.JLabel();
        txtfPontucaoMinima = new javax.swing.JTextField();
        lblPontucaoMaxima = new javax.swing.JLabel();
        txtfPontuacaoMaxima = new javax.swing.JTextField();
        lblPrecisaoPontucao = new javax.swing.JLabel();
        spnPrecisaoPontucao = new javax.swing.JSpinner();
        pnlSistemaPenalizacao = new javax.swing.JPanel();
        lblIncidencia = new javax.swing.JLabel();
        chkbIncidencia = new javax.swing.JCheckBox();
        lblProporcao = new javax.swing.JLabel();
        spnProporcao = new javax.swing.JSpinner();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblTipoProva.setText("Tipode de Prova:");

        cmbbTipoProva.addItem(TipoProva.MULTIPLA_ESCOLHA.getTipo());
        cmbbTipoProva.addItem(TipoProva.VERDADEIRO_FALSO.getTipo());

        if(prova.getTipoProva().equals(TipoProva.MULTIPLA_ESCOLHA)){
            cmbbTipoProva.setSelectedItem(TipoProva.MULTIPLA_ESCOLHA.getTipo());
        }else{
            cmbbTipoProva.setSelectedItem(TipoProva.VERDADEIRO_FALSO.getTipo());
        }
        cmbbTipoProva.setToolTipText("<html>Tipo de Prova a ser corrigida.<br />\nProvas de múltipla escolha podem apresentar <br />respostas como sendo 'a', 'b', 'd' ou 'e'.<br/>\nProvas de verdadeiro ou falso podem apresentar <br />respostas como sendo 'v' ou 'f'.<br/></html>\n");

        lblQntQuestoes.setText("Quantidade de Questões:");

        spnQntQuestoes.setModel(new javax.swing.SpinnerNumberModel(50, 10, 100, 10));
        spnQntQuestoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnlEscalaPontuacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Escala de Pontuação"));

        lblPontucaoMinima.setText("Pontuação Mínima:");

        lblPontucaoMaxima.setText("Pontuação Máxima:");

        lblPrecisaoPontucao.setText("Precisão da pontuação:");

        spnPrecisaoPontucao.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3, 1));

        javax.swing.GroupLayout pnlEscalaPontuacaoLayout = new javax.swing.GroupLayout(pnlEscalaPontuacao);
        pnlEscalaPontuacao.setLayout(pnlEscalaPontuacaoLayout);
        pnlEscalaPontuacaoLayout.setHorizontalGroup(
            pnlEscalaPontuacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEscalaPontuacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEscalaPontuacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEscalaPontuacaoLayout.createSequentialGroup()
                        .addComponent(lblPrecisaoPontucao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnPrecisaoPontucao))
                    .addGroup(pnlEscalaPontuacaoLayout.createSequentialGroup()
                        .addGroup(pnlEscalaPontuacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPontucaoMinima)
                            .addComponent(lblPontucaoMaxima))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEscalaPontuacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfPontuacaoMaxima, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(txtfPontucaoMinima))))
                .addContainerGap())
        );
        pnlEscalaPontuacaoLayout.setVerticalGroup(
            pnlEscalaPontuacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEscalaPontuacaoLayout.createSequentialGroup()
                .addGroup(pnlEscalaPontuacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPontucaoMinima)
                    .addComponent(txtfPontucaoMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEscalaPontuacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPontucaoMaxima)
                    .addComponent(txtfPontuacaoMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEscalaPontuacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecisaoPontucao)
                    .addComponent(spnPrecisaoPontucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSistemaPenalizacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Sistema de Penalização"));

        lblIncidencia.setText("Incidência: ");

        chkbIncidencia.setText("Sim");
        chkbIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbIncidenciaActionPerformed(evt);
            }
        });

        lblProporcao.setText("Proporção: ");

        spnProporcao.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        if(chkbIncidencia.isSelected()){
            spnProporcao.setEnabled(true);
        }else{
            spnProporcao.setEnabled(false);
        }

        javax.swing.GroupLayout pnlSistemaPenalizacaoLayout = new javax.swing.GroupLayout(pnlSistemaPenalizacao);
        pnlSistemaPenalizacao.setLayout(pnlSistemaPenalizacaoLayout);
        pnlSistemaPenalizacaoLayout.setHorizontalGroup(
            pnlSistemaPenalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSistemaPenalizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIncidencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkbIncidencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(lblProporcao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnProporcao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlSistemaPenalizacaoLayout.setVerticalGroup(
            pnlSistemaPenalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSistemaPenalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblIncidencia)
                .addComponent(chkbIncidencia)
                .addComponent(spnProporcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblProporcao))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQntQuestoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnQntQuestoes))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTipoProva)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbbTipoProva, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnSalvar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnCancelar))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlEscalaPontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlSistemaPenalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoProva)
                    .addComponent(cmbbTipoProva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQntQuestoes)
                    .addComponent(spnQntQuestoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlEscalaPontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSistemaPenalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void chkbIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbIncidenciaActionPerformed
        if(chkbIncidencia.isSelected()){
            spnProporcao.setEnabled(true);
        }else{
            spnProporcao.setEnabled(false);
        }
    }//GEN-LAST:event_chkbIncidenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chkbIncidencia;
    private javax.swing.JComboBox cmbbTipoProva;
    private javax.swing.JLabel lblIncidencia;
    private javax.swing.JLabel lblPontucaoMaxima;
    private javax.swing.JLabel lblPontucaoMinima;
    private javax.swing.JLabel lblPrecisaoPontucao;
    private javax.swing.JLabel lblProporcao;
    private javax.swing.JLabel lblQntQuestoes;
    private javax.swing.JLabel lblTipoProva;
    private javax.swing.JPanel pnlEscalaPontuacao;
    private javax.swing.JPanel pnlSistemaPenalizacao;
    private javax.swing.JSpinner spnPrecisaoPontucao;
    private javax.swing.JSpinner spnProporcao;
    private javax.swing.JSpinner spnQntQuestoes;
    private javax.swing.JTextField txtfPontuacaoMaxima;
    private javax.swing.JTextField txtfPontucaoMinima;
    // End of variables declaration//GEN-END:variables
}
