/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package scacp;

import java.util.HashMap;

/**
 *
 * @author cleber
 */
public class QuestoesPainel extends javax.swing.JPanel {
    private int inicioQuestoes, fimQuestoes, numeroInscricao;
    private HashMap<Integer, QuestaoFormulario> questoes;
    private TipoProva tipoProva;
    /**
     * Creates new form FormularioRespostas
     */
    public QuestoesPainel(int numeroInscricao, int inicioQuestoes, int fimQuestoes, TipoProva tipoProva) {
        this.numeroInscricao = numeroInscricao;
        this.inicioQuestoes = inicioQuestoes;
        this.fimQuestoes = fimQuestoes;
        this.tipoProva = tipoProva;
        questoes = new HashMap<>();
        initComponents();
        
        System.out.println("tamanho: " + getPreferredSize());
    }
    
    public String getMarcacao(){
        int contador;
        String marcacao = "";
        for(contador = inicioQuestoes; contador <= fimQuestoes; contador++){
            marcacao += questoes.get(contador).getAlternativa();
        }
        System.out.println("Marcação: " + marcacao);
        return marcacao;
    }
    
    public void setMarcacao(String marcacao){
        int contador, questao;
        for(contador = inicioQuestoes, questao = 0; contador <= fimQuestoes; contador++, questao++){
            questoes.get(contador).setAlternativa(String.format("%c", marcacao.charAt(questao)));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotuloRespostas = new javax.swing.JLabel();
        pnlLateralDireito = new javax.swing.JPanel();
        pnlLateralEsquerdo = new javax.swing.JPanel();
        pnlQuestoes = new javax.swing.JPanel();

        setBackground(new java.awt.Color(216, 133, 50));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(0, 252));
        setLayout(new java.awt.BorderLayout());

        rotuloRespostas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rotuloRespostas.setText(String.format("Questões de %02d a %02d - Inscrição: %07d", inicioQuestoes, fimQuestoes, numeroInscricao));
        add(rotuloRespostas, java.awt.BorderLayout.PAGE_START);

        if(tipoProva == TipoProva.MULTIPLA_ESCOLHA){
            pnlLateralDireito = new scacp.QuestaoMEPainelLateral();
        }else{
            pnlLateralDireito = new scacp.QuestaoVFPainelLateral();
        }

        add(pnlLateralDireito, java.awt.BorderLayout.LINE_END);

        if(tipoProva == TipoProva.MULTIPLA_ESCOLHA){
            pnlLateralEsquerdo = new scacp.QuestaoMEPainelLateral();
        }else{
            pnlLateralEsquerdo = new scacp.QuestaoVFPainelLateral();
        }

        add(pnlLateralEsquerdo, java.awt.BorderLayout.LINE_START);

        pnlQuestoes.setBackground(new java.awt.Color(235, 122, 227));
        pnlQuestoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlQuestoes.setLayout(new javax.swing.BoxLayout(pnlQuestoes, javax.swing.BoxLayout.LINE_AXIS));

        pnlQuestoes.setBackground(new java.awt.Color(166, 166, 166));
        if(tipoProva == TipoProva.MULTIPLA_ESCOLHA){
            for(int cont = inicioQuestoes; cont <= fimQuestoes; cont++){
                questoes.put(cont, new scacp.QuestaoMEFormulario(cont, numeroInscricao));
                pnlQuestoes.add(questoes.get(cont));
            }
        }else{
            for(int cont = inicioQuestoes; cont <= fimQuestoes; cont++){
                questoes.put(cont, new scacp.QuestaoVFFormulario(cont, numeroInscricao));
                pnlQuestoes.add(questoes.get(cont));
            }
        }
        System.out.println("Painel das questões em si: "+pnlQuestoes.getSize());

        add(pnlQuestoes, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlLateralDireito;
    private javax.swing.JPanel pnlLateralEsquerdo;
    private javax.swing.JPanel pnlQuestoes;
    private javax.swing.JLabel rotuloRespostas;
    // End of variables declaration//GEN-END:variables
}
