/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package scacp;

/**
 *
 * @author cleber
 */
public class FormularioQuestoes extends javax.swing.JPanel {
    private int quantidadeQuestoes, numeroInscricao;
    private TipoProva tipoProva;
    /**
     * Creates new form FormularioRespostas
     */
    public FormularioQuestoes(int numeroInscricao, int quantidadeQuestoes, TipoProva tipoProva) {
        this.numeroInscricao = numeroInscricao;
        this.quantidadeQuestoes = quantidadeQuestoes;
        this.tipoProva = tipoProva;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotuloRespostas = new javax.swing.JLabel();
        pnlLateralDireito = new javax.swing.JPanel();
        pnlLateralEsquerdo = new javax.swing.JPanel();
        pnlQuestoes = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        rotuloRespostas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rotuloRespostas.setText(String.format("Questões de 01 a %2d - Inscrição: %7d", quantidadeQuestoes, numeroInscricao));
        add(rotuloRespostas, java.awt.BorderLayout.PAGE_START);

        if(tipoProva == TipoProva.MULTIPLA_ESCOLHA){
            pnlLateralDireito = new PainelLateralQuestaoME();
        }else{
            pnlLateralDireito = new PainelLateralQuestaoVF();
        }

        add(pnlLateralDireito, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout pnlLateralEsquerdoLayout = new javax.swing.GroupLayout(pnlLateralEsquerdo);
        pnlLateralEsquerdo.setLayout(pnlLateralEsquerdoLayout);
        pnlLateralEsquerdoLayout.setHorizontalGroup(
            pnlLateralEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlLateralEsquerdoLayout.setVerticalGroup(
            pnlLateralEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );

        if(tipoProva == TipoProva.MULTIPLA_ESCOLHA){
            pnlLateralEsquerdo = new PainelLateralQuestaoME();
        }else{
            pnlLateralEsquerdo = new PainelLateralQuestaoVF();
        }

        add(pnlLateralEsquerdo, java.awt.BorderLayout.LINE_START);

        pnlQuestoes.setBackground(new java.awt.Color(122, 108, 94));

        pnlQuestoes.setBackground(new java.awt.Color(166, 166, 166));
        if(tipoProva == TipoProva.MULTIPLA_ESCOLHA){
            for(int cont = 1; cont <= quantidadeQuestoes; cont++){
                pnlQuestoes.add(new FormularioQuestaoME(cont, numeroInscricao));
            }
        }else{
            for(int cont = 1; cont <= quantidadeQuestoes; cont++){
                pnlQuestoes.add(new FormularioQuestaoVF(cont, numeroInscricao));
            }
        }

        add(pnlQuestoes, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlLateralDireito;
    private javax.swing.JPanel pnlLateralEsquerdo;
    private javax.swing.JPanel pnlQuestoes;
    private javax.swing.JLabel rotuloRespostas;
    // End of variables declaration//GEN-END:variables
}
