/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package scacp;

/**
 *
 * @author cleber
 */
public class FormularioRespostas extends javax.swing.JPanel {
    int quantidadeQuestoes, numeroInscricao;
    TipoProva tipoProva;
    /**
     * Creates new form FormularioRespostas
     */
    public FormularioRespostas(int numeroInscricao, int quantidadeQuestoes, TipoProva tipoProva) {
        this.numeroInscricao = numeroInscricao;
        this.quantidadeQuestoes = quantidadeQuestoes;
        this.tipoProva = tipoProva;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotuloRespostas = new javax.swing.JLabel();
        lblLegendaMarcacaoEsquerda = new javax.swing.JLabel();
        lblLegendaMarcacaoDireita = new javax.swing.JLabel();
        painelAlternativas = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        rotuloRespostas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rotuloRespostas.setText(String.format("Questões de 01 a %2d - Inscrição: %7d", quantidadeQuestoes, numeroInscricao));
        add(rotuloRespostas, java.awt.BorderLayout.PAGE_START);

        lblLegendaMarcacaoEsquerda.setText("Respostas");
        if(tipoProva == TipoProva.MULTIPLA_ESCOLHA){
            lblLegendaMarcacaoEsquerda.setText("<html>Respostas<br/>(a)<br/>(b)<br/>(c)<br/>(d)<br/>(e)<br/>(*) ou (#)</html>");
        }else{
            lblLegendaMarcacaoEsquerda.setText("<html>Respostas<br/>(V)<br/>(F)<br/>(*) ou (#)</html>");
        }
        lblLegendaMarcacaoEsquerda.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblLegendaMarcacaoEsquerda, java.awt.BorderLayout.LINE_START);

        lblLegendaMarcacaoDireita.setText("Respostas");
        if(tipoProva == TipoProva.MULTIPLA_ESCOLHA){
            lblLegendaMarcacaoDireita.setText("<html>Respostas<br/>(a)<br/>(b)<br/>(c)<br/>(d)<br/>(e)<br/>(*) ou (#)</html>");
        }else{
            lblLegendaMarcacaoDireita.setText("<html>Respostas<br/>(V)<br/>(F)<br/>(*) ou (#)</html>");
        }
        lblLegendaMarcacaoDireita.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblLegendaMarcacaoDireita, java.awt.BorderLayout.LINE_END);

        painelAlternativas.setBackground(new java.awt.Color(166, 166, 166));
        for(int cont = 1; cont <= quantidadeQuestoes; cont++){
            painelAlternativas.add(new FormularioQuestao1(tipoProva, cont));
        }
        add(painelAlternativas, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLegendaMarcacaoDireita;
    private javax.swing.JLabel lblLegendaMarcacaoEsquerda;
    private javax.swing.JPanel painelAlternativas;
    private javax.swing.JLabel rotuloRespostas;
    // End of variables declaration//GEN-END:variables
}
